Favor using semver directly from npm than the os package
The os package have unbundled dependencies which currently results in following stacktrace when trying to publish the 3.0.0 release:

Error: Cannot find module 'lru-cache'
Require stack:
- /usr/share/nodejs/semver/classes/range.js
- /usr/share/nodejs/semver/classes/comparator.js
- /usr/share/nodejs/semver/index.js
- /usr/share/nodejs/semver/bin/semver.js